name: Mirror to Nurasa Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to deploy repo
        env:
          MY_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Cek jika token kosong (akan terlihat di log GitHub Actions)
          if [ -z "$MY_TOKEN" ]; then
            echo "ERROR: GH_TOKEN is empty. Please check your Repository Secrets."
            exit 1
          fi

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          # Gunakan format URL yang lebih ketat
          git remote add deploy "https://pilarlabsid:${MY_TOKEN}@github.com/pilarlabsid/nurasa.git" || \
          git remote set-url deploy "https://pilarlabsid:${MY_TOKEN}@github.com/pilarlabsid/nurasa.git"
          
          git push deploy main --force
